services:
  next:
    container_name: nextJS
    image: node:20.11.0
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    working_dir: '/app'
    command: sh -c 'npm install --force && npm run dev'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: shopList_DB
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
