import { Luckiest_Guy } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

const LuckiestGuy = Luckiest_Guy({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${LuckiestGuy.className} h-dvh max-h-dvh antialiased`}>{children}</body>
    </html>
  );
}
